git:
    # Once we start using the recordings for testing, remove this.
    submodules: false
language: cpp
install:
    - "sudo add-apt-repository -y ppa:eighthave/openni"
    - "sudo apt-get update -y"
    - "sudo apt-get install -y libopenni-dev freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev libxmu-dev"
script:
    - "mkdir build"
    - "cd build"
    - "cmake .."
    - "make"

# vim:sw=4:sts=2:et
